version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-core_crm
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: johndoe  
      POSTGRES_PASSWORD: randompassword  
      POSTGRES_DB: mydb 
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
